//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFTradeExtension.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFTradeExtension.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Неверный AppId 的本地化字符串。
        /// </summary>
        internal static string AppIdInvalid {
            get {
                return ResourceManager.GetString("AppIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Параметр неверный 的本地化字符串。
        /// </summary>
        internal static string ArgumentInvalidAppIds {
            get {
                return ResourceManager.GetString("ArgumentInvalidAppIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Неправильный параметр, пример: -p 2 -l 20 (вторая страница, 20 предмет на странице) 的本地化字符串。
        /// </summary>
        internal static string ArgumentInvalidFSL {
            get {
                return ResourceManager.GetString("ArgumentInvalidFSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Недопустимый параметр, пример: 730 2 Ссылка на трейд 的本地化字符串。
        /// </summary>
        internal static string ArgumentInvalidSCS {
            get {
                return ResourceManager.GetString("ArgumentInvalidSCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppId и SetCount должны быть больше чем 0 的本地化字符串。
        /// </summary>
        internal static string ArgumentInvalidSCS2 {
            get {
                return ResourceManager.GetString("ArgumentInvalidSCS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册失败 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterFailed {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册成功 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterSuccess {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 В инвентаре отсутствуют карточки 的本地化字符串。
        /// </summary>
        internal static string CardInventoryIsEmpty {
            get {
                return ResourceManager.GetString("CardInventoryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Пустой ответ 的本地化字符串。
        /// </summary>
        internal static string CartEmptyResponse {
            get {
                return ResourceManager.GetString("CartEmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Успешная очиститка старых бекапов плагина 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackup {
            get {
                return ResourceManager.GetString("CleanUpOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Не удалось очистить старые бекапы плагина 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackupFailed {
            get {
                return ResourceManager.GetString("CleanUpOldBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数无效 CSDELISTING [BotNames] [ClassId], 不指定 ClassId 时下架全部物品 的本地化字符串。
        /// </summary>
        internal static string CsDeListingItemArgsTips {
            get {
                return ResourceManager.GetString("CsDeListingItemArgsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Параметр CSMARKETHISTORY недействителен  [BotNames] [ClassId] , если ClassId не указан, то все элементы будут помещены на продажу 的本地化字符串。
        /// </summary>
        internal static string CsMarketHistoryArgsTips {
            get {
                return ResourceManager.GetString("CsMarketHistoryArgsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: Всего {1} карточек, {2} карточек в наборе, Всего {3} наборов + {4} карточек, Торгуемых наборов {5} + {6} карточек 的本地化字符串。
        /// </summary>
        internal static string CurrentCardInventoryShow {
            get {
                return ResourceManager.GetString("CurrentCardInventoryShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ru-RU 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功下架了 {0} 个物品 的本地化字符串。
        /// </summary>
        internal static string DeListingSuccess {
            get {
                return ResourceManager.GetString("DeListingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Готово 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ошибка 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: &quot;ASFTradeExtension.EULA&quot; не принят, некоторые функции отключены 的本地化字符串。
        /// </summary>
        internal static string EulaWarning {
            get {
                return ResourceManager.GetString("EulaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Предполагаемое количество ожидаемых отправления наборов {0}, всего карточек {1} 的本地化字符串。
        /// </summary>
        internal static string ExpectToSendCardInfo {
            get {
                return ResourceManager.GetString("ExpectToSendCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Неудачно 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ошибка автоматического получения ссылки на транзакцию 的本地化字符串。
        /// </summary>
        internal static string FetchTradeLinkFailed {
            get {
                return ResourceManager.GetString("FetchTradeLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Неверный ClassId 的本地化字符串。
        /// </summary>
        internal static string InvalidClassId {
            get {
                return ResourceManager.GetString("InvalidClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Состояние инвентаря до совершения операции: 的本地化字符串。
        /// </summary>
        internal static string InventoryStatusBeforeTrade {
            get {
                return ResourceManager.GetString("InventoryStatusBeforeTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Всего {0} предметов, поставленных на продажу {1} 的本地化字符串。
        /// </summary>
        internal static string ItemListingSuccess {
            get {
                return ResourceManager.GetString("ItemListingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;Всего {0} предметов, поставленных на продажу, Ожидание 2FA подтверждения 的本地化字符串。
        /// </summary>
        internal static string ItemListSuccessWaitConfirm {
            get {
                return ResourceManager.GetString("ItemListSuccessWaitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ========================================== 的本地化字符串。
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Не удалось считать информацию инвентаря из-за сетевой ошибки 的本地化字符串。
        /// </summary>
        internal static string LoadInventoryFailedNetworkError {
            get {
                return ResourceManager.GetString("LoadInventoryFailedNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Результат с несколькими строками: 的本地化字符串。
        /// </summary>
        internal static string MultipleLineResult {
            get {
                return ResourceManager.GetString("MultipleLineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Сетевая ошибка 的本地化字符串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Карточки отсутствуют 的本地化字符串。
        /// </summary>
        internal static string NoAvilableCards {
            get {
                return ResourceManager.GetString("NoAvilableCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 При текущих настройках ничего не отображается 的本地化字符串。
        /// </summary>
        internal static string NoAvilableItemToShow {
            get {
                return ResourceManager.GetString("NoAvilableItemToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Нет доступных ботов 的本地化字符串。
        /// </summary>
        internal static string NoBotsAvilable {
            get {
                return ResourceManager.GetString("NoBotsAvilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Информация отсутствует 的本地化字符串。
        /// </summary>
        internal static string NoInformation {
            get {
                return ResourceManager.GetString("NoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Отсутствие предметов CSGO для продажи с текущими фильтрами 的本地化字符串。
        /// </summary>
        internal static string NoSelingCsItemInFilter {
            get {
                return ResourceManager.GetString("NoSelingCsItemInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Отсутствие предметов CSGO для продажи 的本地化字符串。
        /// </summary>
        internal static string NoSellingCsItem {
            get {
                return ResourceManager.GetString("NoSellingCsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Разработано Chr_, email chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐安装 ASFEnhance, 支持自动更新插件 的本地化字符串。
        /// </summary>
        internal static string PluginStandalongMode {
            get {
                return ResourceManager.GetString("PluginStandalongMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Версия {1} 的本地化字符串。
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Параметр SELLCSITEM недействителен [BotNames] [ClassId] , если ClassId не указан, то все элементы будут помещены на продажу, Продать все, когда ClassId равен -1 的本地化字符串。
        /// </summary>
        internal static string SellCsItemArgsTips {
            get {
                return ResourceManager.GetString("SellCsItemArgsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Неверный SENDCSITEM [Bots] [ClassId] Количество предметов для отправки каждому боту, если ClassId не указан, то будут отправлены все доступные для торговли/обмена предметы, в противном случае будут отправлены только указанные предметы 的本地化字符串。
        /// </summary>
        internal static string SendCsItemArgsTips {
            get {
                return ResourceManager.GetString("SendCsItemArgsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Не удалось отправить трейд, AppId может быть не верным 的本地化字符串。
        /// </summary>
        internal static string SendTradeFailedAppIdInvalid {
            get {
                return ResourceManager.GetString("SendTradeFailedAppIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Не удалось отправить трейд, недостаточное количество карт для обмена 的本地化字符串。
        /// </summary>
        internal static string SendTradeFailedNoEnoughCards {
            get {
                return ResourceManager.GetString("SendTradeFailedNoEnoughCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Отправить трейд {0} -&gt; {1} Отклонено, нет предметов в наличии 的本地化字符串。
        /// </summary>
        internal static string SendTradeFailedNoItemAvilable {
            get {
                return ResourceManager.GetString("SendTradeFailedNoItemAvilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Трейд отправлен {0} 的本地化字符串。
        /// </summary>
        internal static string SendTradeResult {
            get {
                return ResourceManager.GetString("SendTradeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Отправить трейд {0} -&gt; {1}, количество предметов {2}, {3} 的本地化字符串。
        /// </summary>
        internal static string SengTradeSuccess {
            get {
                return ResourceManager.GetString("SengTradeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Неверный SteamId 的本地化字符串。
        /// </summary>
        internal static string SteamIdInvalid {
            get {
                return ResourceManager.GetString("SteamIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Успех 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Подтверждение 2FA {0} 的本地化字符串。
        /// </summary>
        internal static string TFAConfirmResult {
            get {
                return ResourceManager.GetString("TFAConfirmResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} Количество {2} 的本地化字符串。
        /// </summary>
        internal static string ThreeItemWithNum {
            get {
                return ResourceManager.GetString("ThreeItemWithNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string TwoItem {
            get {
                return ResourceManager.GetString("TwoItem", resourceCulture);
            }
        }
    }
}
