//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFTradeExtension.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFTradeExtension.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 无效 AppId 的本地化字符串。
        /// </summary>
        internal static string AppIdInvalid {
            get {
                return ResourceManager.GetString("AppIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入参数 AppIds 无效 的本地化字符串。
        /// </summary>
        internal static string ArgumentInvalidAppIds {
            get {
                return ResourceManager.GetString("ArgumentInvalidAppIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数有误, 示例: -p 2 -l 20 (第二页, 每页20条) 的本地化字符串。
        /// </summary>
        internal static string ArgumentInvalidFSL {
            get {
                return ResourceManager.GetString("ArgumentInvalidFSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数无效, 示例 730 2 交易链接 的本地化字符串。
        /// </summary>
        internal static string ArgumentInvalidSCS {
            get {
                return ResourceManager.GetString("ArgumentInvalidSCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppId 和 SetCount 必须大于0 的本地化字符串。
        /// </summary>
        internal static string ArgumentInvalidSCS2 {
            get {
                return ResourceManager.GetString("ArgumentInvalidSCS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册失败 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterFailed {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册成功 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterSuccess {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡牌库存为空 的本地化字符串。
        /// </summary>
        internal static string CardInventoryIsEmpty {
            get {
                return ResourceManager.GetString("CardInventoryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应为空 的本地化字符串。
        /// </summary>
        internal static string CartEmptyResponse {
            get {
                return ResourceManager.GetString("CartEmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份已经自动清理 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackup {
            get {
                return ResourceManager.GetString("CleanUpOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份清理失败 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackupFailed {
            get {
                return ResourceManager.GetString("CleanUpOldBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数无效 CSDELISTING [BotNames] [ClassId], 不指定 ClassId 时下架全部物品 的本地化字符串。
        /// </summary>
        internal static string CsDeListingItemArgsTips {
            get {
                return ResourceManager.GetString("CsDeListingItemArgsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数无效 CSMARKETHISTORY [BotNames] [ClassId] , 不指定 ClassId 时下架全部物品 的本地化字符串。
        /// </summary>
        internal static string CsMarketHistoryArgsTips {
            get {
                return ResourceManager.GetString("CsMarketHistoryArgsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 总计 {1}张, 每套 {2}张, 总计 {3}套 +{4}张, 可交易 {5}套 +{6}张 的本地化字符串。
        /// </summary>
        internal static string CurrentCardInventoryShow {
            get {
                return ResourceManager.GetString("CurrentCardInventoryShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-Hans 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功下架了 {0} 个物品 的本地化字符串。
        /// </summary>
        internal static string DeListingSuccess {
            get {
                return ResourceManager.GetString("DeListingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 尚未同意 ASFEnhance.EULA, 部分命令已禁用 的本地化字符串。
        /// </summary>
        internal static string EulaWarning {
            get {
                return ResourceManager.GetString("EulaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预计发送 {0} 套, 共 {1} 张 卡牌 的本地化字符串。
        /// </summary>
        internal static string ExpectToSendCardInfo {
            get {
                return ResourceManager.GetString("ExpectToSendCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动获取交易链接失败 的本地化字符串。
        /// </summary>
        internal static string FetchTradeLinkFailed {
            get {
                return ResourceManager.GetString("FetchTradeLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部错误 的本地化字符串。
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 ClassId 的本地化字符串。
        /// </summary>
        internal static string InvalidClassId {
            get {
                return ResourceManager.GetString("InvalidClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易前库存状态: 的本地化字符串。
        /// </summary>
        internal static string InventoryStatusBeforeTrade {
            get {
                return ResourceManager.GetString("InventoryStatusBeforeTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共计 {0} 个物品上架 {1} 的本地化字符串。
        /// </summary>
        internal static string ItemListingSuccess {
            get {
                return ResourceManager.GetString("ItemListingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共计 {0} 个物品上架, 等待手动确认 的本地化字符串。
        /// </summary>
        internal static string ItemListSuccessWaitConfirm {
            get {
                return ResourceManager.GetString("ItemListSuccessWaitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ========================================== 的本地化字符串。
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络异常, 读取库存信息失败 的本地化字符串。
        /// </summary>
        internal static string LoadInventoryFailedNetworkError {
            get {
                return ResourceManager.GetString("LoadInventoryFailedNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行结果: 的本地化字符串。
        /// </summary>
        internal static string MultipleLineResult {
            get {
                return ResourceManager.GetString("MultipleLineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络错误 的本地化字符串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无卡牌 的本地化字符串。
        /// </summary>
        internal static string NoAvilableCards {
            get {
                return ResourceManager.GetString("NoAvilableCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置下无可显示的内容 的本地化字符串。
        /// </summary>
        internal static string NoAvilableItemToShow {
            get {
                return ResourceManager.GetString("NoAvilableItemToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用机器人 的本地化字符串。
        /// </summary>
        internal static string NoBotsAvilable {
            get {
                return ResourceManager.GetString("NoBotsAvilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无信息 的本地化字符串。
        /// </summary>
        internal static string NoInformation {
            get {
                return ResourceManager.GetString("NoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤条件下无正在出售的CSGO物品 的本地化字符串。
        /// </summary>
        internal static string NoSelingCsItemInFilter {
            get {
                return ResourceManager.GetString("NoSelingCsItemInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无正在出售的CSGO物品 的本地化字符串。
        /// </summary>
        internal static string NoSellingCsItem {
            get {
                return ResourceManager.GetString("NoSellingCsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件作者: Chr_, 联系方式: chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱发电: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐安装 ASFEnhance, 支持自动更新插件. 的本地化字符串。
        /// </summary>
        internal static string PluginStandalongMode {
            get {
                return ResourceManager.GetString("PluginStandalongMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 版本 {1} 的本地化字符串。
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数无效 SELLCSITEM ClassId 数量 价格, 数量为-1时出售全部 的本地化字符串。
        /// </summary>
        internal static string SellCsItemArgsTips {
            get {
                return ResourceManager.GetString("SellCsItemArgsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数无效 SENDCSITEM [Bots] [ClassId] 发给每个Bot的数量, ClassId未指定时发送全部可交易物品, 否则只发送指定的物品 的本地化字符串。
        /// </summary>
        internal static string SendCsItemArgsTips {
            get {
                return ResourceManager.GetString("SendCsItemArgsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送交易失败, AppId 可能无效 的本地化字符串。
        /// </summary>
        internal static string SendTradeFailedAppIdInvalid {
            get {
                return ResourceManager.GetString("SendTradeFailedAppIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易报价发送成功失败, 可交易卡牌数量不足 的本地化字符串。
        /// </summary>
        internal static string SendTradeFailedNoEnoughCards {
            get {
                return ResourceManager.GetString("SendTradeFailedNoEnoughCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送交易报价 {0} -&gt; {1} 失败, 无可用物品 的本地化字符串。
        /// </summary>
        internal static string SendTradeFailedNoItemAvilable {
            get {
                return ResourceManager.GetString("SendTradeFailedNoItemAvilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易报价发送{0} 的本地化字符串。
        /// </summary>
        internal static string SendTradeResult {
            get {
                return ResourceManager.GetString("SendTradeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送交易报价 {0} -&gt; {1}, 物品数量 {2}, {3} 的本地化字符串。
        /// </summary>
        internal static string SendTradeSuccess {
            get {
                return ResourceManager.GetString("SendTradeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamId 无效 的本地化字符串。
        /// </summary>
        internal static string SteamIdInvalid {
            get {
                return ResourceManager.GetString("SteamIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2FA自动确认{0} 的本地化字符串。
        /// </summary>
        internal static string TFAConfirmResult {
            get {
                return ResourceManager.GetString("TFAConfirmResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} 数量 {2} 的本地化字符串。
        /// </summary>
        internal static string ThreeItemWithNum {
            get {
                return ResourceManager.GetString("ThreeItemWithNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string TwoItem {
            get {
                return ResourceManager.GetString("TwoItem", resourceCulture);
            }
        }
    }
}
